import { Compression } from "parquet-wasm/node";
import { convertSingle } from "../../src/converter";

/**
 * Get the first Parquet file generated by convertSingle, or return null
 * if no Parquet file was generated.
 *
 * @param inputPath the path to a CloudTrail JSON file
 * @param eventTimePrefix a time prefix to filter records by (or "" for no filtering)
 */
export async function getFirstConversion(inputPath: string, eventTimePrefix: string) {
  for await (const pq of convertSingle(
    [inputPath], eventTimePrefix,
    100,
    1,
    Compression.SNAPPY,
  )) {
    if (pq)
      return pq;
  }

  return null;
}
